
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 12 00:31:08 COT 2015
//----------------------------------------------------

package codigo;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 2;
  public static final int IDENT = 9;
  public static final int NUMBER = 8;
  public static final int EOF = 0;
  public static final int ASSIGN = 5;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int NOT = 4;
  public static final int LPAREN = 6;
  public static final int OR = 3;
}

